language: java
branches:
  only:
  - master
  - /^\d+\.\d+$/
jobs:
  include:
    - stage: test
      name: "OracleJDK 8"
      jdk: oraclejdk8
      script: mvn -q clean verify -B
    - if: type != pull_request
      name: "OpenJDK 11"
      jdk: openjdk11
      script: mvn -q clean verify -B
    - if: type != pull_request
      name: "OracleJDK 8 / native transport"
      jdk: oraclejdk8
      script: mvn -q clean verify -B -PtestNativeTransport
    - if: type != pull_request
      name: "OracleJDK 8 / domain sockets"
      jdk: oraclejdk8
      script: mvn -q clean verify -B -PtestDomainSockets
    - stage: deploy
      name: "Deploy to Sonatype's snapshots repository"
      if: type != pull_request
      script: bash .travis.deploy.artifacts.sh
notifications:
  email:
    recipients:
      - vertx3-ci@googlegroups.com
    on_success: always
    on_failure: always
